### ISSUE TITLE
Add splash screen

### ISSUE THREAD

**Issue by Feras-dev** [Feras-dev/pomodoro#22]
Load this image upon launching the app for no more than a few second: 
![Pomodoro](https://user-images.githubusercontent.com/72912013/115139988-b1b7e400-a03d-11eb-97e0-e78ce05b1cdb.png)

Use this tutorial: https://flutter.dev/docs/development/ui/advanced/splash-screen#creating-a-custom-splashscreen

**Comment by saurabh-dk** [comment]
fixed by #51
