### ISSUE TITLE
Overflowed pixels at the bottom of addTask screen when keyboard appears

### ISSUE THREAD

**Issue by Feras-dev** [Feras-dev/pomodoro#43]
See PR for one-liner fix.
Issue:
![2021-05-07 18_03_25-Window](https://user-images.githubusercontent.com/72912013/117473727-ee9f3880-af62-11eb-846a-34333099140f.png)

test after fix:
![2021-05-07 18_10_15-Window](https://user-images.githubusercontent.com/72912013/117473756-f5c64680-af62-11eb-997d-bd3e218e4bb6.png)

**Comment by saurabh-dk** [comment]
Fixed by #44
