### ISSUE TITLE
Design Task class (needs more discussion)

### ISSUE THREAD

**Issue by Feras-dev** [Feras-dev/pomodoro#7]

**Comment by saurabh-dk** [comment]
Saving a List of Tasks in shared_preferences
https://stackoverflow.com/questions/61316208/how-to-save-listobject-to-sharedpreferences-flutter

**Comment by Feras-dev** [comment]
Reduce scope and add DoD. @saurabh-dk

**Comment by saurabh-dk** [comment]
DoD:
Task class should
1. Support for Priority Level.
2. Contain working methods to encode and decode JSON.
